## Introduction to pandas data structures (series and DataFrames)

1. Series-a series is one-dimensional array-like object containint a sequence of values (of similar types to NumPy types) and an associated array of data labels, *index*. 


In [2]:
import numpy as np
import pandas as pd

In [3]:
# example 
obj=pd.Series([4,7,-5,3])
obj #Since we did not specify an index for the data, a default one consisting of the integers 0 through N - 1 (where N is the length of the
#data) is created.

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
#You can get the array representation and index object of the Series via its values and index attributes, respectively:

print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [5]:
#Often it will be desirable to create a Series with an index identifying each data point with a label:
obj2=pd.Series([4,7,-5,3],index=["a","b","c","d"])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [6]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
#Compared with NumPy arrays, you can use labels in the index when selecting single values or a set of values:
#example
print (obj2['b'])
print (obj2[['a','b']])#list of indices

7
a    4
b    7
dtype: int64


In [8]:
#Using NumPy functions or NumPy-like operations, such as filtering with a boolean
#array, scalar multiplication, or applying math functions, will preserve the index-value link
obj2[obj2>0]

a    4
b    7
d    3
dtype: int64

In [9]:
np.exp(obj2)

a      54.598150
b    1096.633158
c       0.006738
d      20.085537
dtype: float64

In [10]:
'e' in obj2

False

In [11]:
#Should you have data contained in a Python dict, you can create a Series from it by passing the dict:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
# When you are only passing a dict, the index in the resulting Series will have the dict’s
# keys in sorted order. You can override this by passing the dict keys in the order you
# want them to appear in the resulting Series:
states = ['Carlifonia', 'Ohio', 'Oregon', 'Texas']
obj4=pd.Series(sdata,index=states)
obj4#no value for 'California' was found, it appears as NaN (not a number), which is considered in pandas to mark missing or NA values.


Carlifonia        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
#Both the Series object itself and its index have a name attribute, which integrates with other key areas of pandas functionality. 
#When you set this attribute, it helps in identifying what the data in the Series pertains to, especially useful 
#when working with multiple series or when the series is transformed into a DataFrame
obj4.name = 'population'
obj4.index.name = 'state'
obj4


state
Carlifonia        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## Data Frame
A DataFrame is a represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type(Numeric, string, boolean, etc)-sort of a dic of series all sharing the same index. 

In [14]:
#example 
data ={'state':['Ohio','Luisianna','New York','New Jersey','Nevada','Pennyslvania'],
       'year':[2000,2001,2002,2003,2004,2005],
       'pop':[1.5,1.7,3.6,2.4,2.9,2.9]}
frame=pd.DataFrame(data)
frame

state  year  pop
0          Ohio  2000  1.5
1     Luisianna  2001  1.7
2      New York  2002  3.6
3    New Jersey  2003  2.4
4        Nevada  2004  2.9
5  Pennyslvania  2005  2.9

In [15]:
#If you specify a sequence of columns, the DataFrame’s columns will be arranged in that order
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year         state  pop
0  2000          Ohio  1.5
1  2001     Luisianna  1.7
2  2002      New York  3.6
3  2003    New Jersey  2.4
4  2004        Nevada  2.9
5  2005  Pennyslvania  2.9

In [16]:
#Columns can be modified by assignment. For example, the empty 'debt' column
#could be assigned a scalar value or an array of values:
frame['debt']=np.arange(6.)
frame

state  year  pop  debt
0          Ohio  2000  1.5   0.0
1     Luisianna  2001  1.7   1.0
2      New York  2002  3.6   2.0
3    New Jersey  2003  2.4   3.0
4        Nevada  2004  2.9   4.0
5  Pennyslvania  2005  2.9   5.0

In [17]:
#When you are assigning lists or arrays to a column, the value’s length must match the
#length of the DataFrame. If you assign a Series, its labels will be realigned exactly to
#the DataFrame’s index, inserting missing values in any holes:
val=pd.Series([-1.3,-4.2,-1.4],index=[1,3,4])
frame.debt=val

In [18]:
frame

state  year  pop  debt
0          Ohio  2000  1.5   NaN
1     Luisianna  2001  1.7  -1.3
2      New York  2002  3.6   NaN
3    New Jersey  2003  2.4  -4.2
4        Nevada  2004  2.9  -1.4
5  Pennyslvania  2005  2.9   NaN

In [19]:
#Assigning a column that doesn’t exist will create a new column. The del keyword will delete columns as with a dict.
#As an example of del, I first add a new column of boolean values where the state column equals 'Ohio':
frame['color'] = np.where(frame.index % 2 == 0, 'red', 'blue')
frame

state  year  pop  debt color
0          Ohio  2000  1.5   NaN   red
1     Luisianna  2001  1.7  -1.3  blue
2      New York  2002  3.6   NaN   red
3    New Jersey  2003  2.4  -4.2  blue
4        Nevada  2004  2.9  -1.4   red
5  Pennyslvania  2005  2.9   NaN  blue

In [20]:
frame.columns

Index(['state', 'year', 'pop', 'debt', 'color'], dtype='object')

In [21]:
#A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute:
frame.year # or frame["year"]

0    2000
1    2001
2    2002
3    2003
4    2004
5    2005
Name: year, dtype: int64

In [22]:
#As an example of del, I first add a new column of boolean values where the state column equals 'Ohio':
frame['eastern'] = frame.state == 'Ohio'
frame

state  year  pop  debt color  eastern
0          Ohio  2000  1.5   NaN   red     True
1     Luisianna  2001  1.7  -1.3  blue    False
2      New York  2002  3.6   NaN   red    False
3    New Jersey  2003  2.4  -4.2  blue    False
4        Nevada  2004  2.9  -1.4   red    False
5  Pennyslvania  2005  2.9   NaN  blue    False

In [23]:
del frame["eastern"]
frame 

state  year  pop  debt color
0          Ohio  2000  1.5   NaN   red
1     Luisianna  2001  1.7  -1.3  blue
2      New York  2002  3.6   NaN   red
3    New Jersey  2003  2.4  -4.2  blue
4        Nevada  2004  2.9  -1.4   red
5  Pennyslvania  2005  2.9   NaN  blue

In [24]:
#Another form of data is nested dict of dicts: 
pop={'nevada':{2001:2.4,2002:2.9},
     'ohio':{2000:1.5, 2001:1.7,2002:3.6}}

In [25]:
#If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys
#as the columns and the inner keys as the row indices:
frame3=pd.DataFrame(pop)
frame3

nevada  ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [26]:
#The keys in the inner dicts are combined and sorted to form the index in the result.
#This isn’t true if an explicit index is specified:
frame4=pd.DataFrame(pop, index=[2001, 2002, 2003])
frame4


nevada  ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [27]:
#one can transpose a data frame in a similar way to numpy. 
frame3.T

2001  2002  2000
nevada   2.4   2.9   NaN
ohio     1.7   3.6   1.5

In [28]:
frame3

nevada  ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [29]:
#If a DataFrame’s index and columns have their name attributes set, these will also be displayed.
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  nevada  ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [30]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

## Index Objects 
pandas’s Index objects are responsible for holding the axis labels and other metadata (like the axis name or names). Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index.Some users will not often take advantage of the capabilities provided by indexes, but because some operations will yield results containing indexed data, it’s important to understand how they
work.


Some Index methods and properties

|Method |Description
------- |-----------
|append |Concatenate with additional Index objects, producing a new Index
|difference |Compute set difference as an Index
|intersection |Compute set intersection
|union |Compute set union
|isin |Compute boolean array indicating whether each value is contained in the passed collection
|delete |Compute new Index with element at index i deleted
|drop |Compute new Index by deleting passed values
|insert |Compute new Index by inserting element at index i
|is_monotonic |Returns True if each element is greater than or equal to the previous element
|is_unique |Returns True if the Index has no duplicate values
|unique |Compute the array of unique values in the Index





In [31]:
obj=pd.Series(range(3), index=['a', 'b', 'c'])

In [32]:
index=obj.index

In [33]:
index

Index(['a', 'b', 'c'], dtype='object')

In [34]:
index[1:]

Index(['b', 'c'], dtype='object')

In [35]:
index[1]='d' #general a type error
#Index objects are immutable and thus can’t be modified by the user:


TypeError: Index does not support mutable operations

In [ ]:
#Immutability makes it safer to share Index objects among data structures
labels=pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int32')

In [ ]:
obj2=pd.Series([1.5,2.5,0], index=labels)
obj2

0    1.5
1    2.5
2    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

 ## Essential Functionality
 Reindexing-An important method on pandas objects is reindex, which means to create a new
object with the data conformed to a new index. 

In [ ]:
#An example
obj=pd.Series([4.5, 3,5,6,7], index=['d', 'b', 'a','c','e'])
obj

d    4.5
b    3.0
a    5.0
c    6.0
e    7.0
dtype: float64

In [ ]:
#Calling reindex on this Series rearranges the data according to the new index, 
#introducing missing values if any index values were not already present.
obj2=obj.reindex(['a','b','c','d','f'])
obj2

a    5.0
b    3.0
c    6.0
d    4.5
f    NaN
dtype: float64

In [ ]:
#For ordered data like time series, it may be desirable to do some interpolation or filling of values when reindexing. The method option allows us to do this, using a
#method such as ffill, which forward-fills the values
obj5=pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj5

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj5.reindex(range(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
#With DataFrame, reindex can alter either the (row) index, columns, or both. When
#passed only a sequence, it reindexes the rows in the result.
frame6=pd.DataFrame(np.arange(9).reshape((3,3)), 
                    index=['a','c','d'],
                    columns=['ohio','texas','Carlifornia'])
frame6


ohio  texas  Carlifornia
a     0      1            2
c     3      4            5
d     6      7            8

In [ ]:
frame7=frame6.reindex(['a','b','c','d'])
frame7

ohio  texas  Carlifornia
a   0.0    1.0          2.0
b   NaN    NaN          NaN
c   3.0    4.0          5.0
d   6.0    7.0          8.0

In [ ]:
frame8=frame7.T

a    0
b    3
c    0
d    0
dtype: int64

In [ ]:
#As we’ll explore in more detail, you can reindex more succinctly by label-indexing
#with loc, and many users prefer to use it exclusively
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

frame6



ohio  texas  Carlifornia
a     0      1            2
c     3      4            5
d     6      7            8

In [ ]:
frame6.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

 Reindex function arguments
| Argument     | Description |
|--------------|-------------|
| index        | New sequence to use as index. Can be Index instance or any other sequence-like Python data structure. An Index will be used exactly as is without any copying. |
| method       | Interpolation (fill) method; 'ffill' fills forward, while 'bfill' fills backward. |
| fill_value   | Substitute value to use when introducing missing data by reindexing. |
| limit        | When forward- or backfilling, maximum size gap (in number of elements) to fill. |
| tolerance    | When forward- or backfilling, maximum size gap (in absolute numeric distance) to fill for inexact matches. |
| level        | Match simple Index on level of MultiIndex; otherwise select subset of. |
| copy         | If True, always copy underlying data even if new index is equivalent to old index; if False, do not copy the data when the indexes are equivalent. |


Indexing, Selection, and Filtering

Series indexing (obj[...]) works analogously to NumPy array indexing, except you
can use the Series’s index values instead of only integers. Here are some examples of
this:

In [ ]:
obj1=pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj1

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
#Selection with loc and iloc
#They enable you to select a subset of the rows and columns from a
#DataFrame with NumPy-like notation using either axis labels (loc) or integers (iloc).
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])


In [ ]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [ ]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [ ]:
#Both indexing functions work with slices in addition to single labels or lists of labels:
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

Indexing options with DataFrame
| Type                | Notes                                                                                                                                                  |
|---------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
| df[val]             | Select single column or sequence of columns from the DataFrame; special case conveniences: boolean array (filter rows), slice (slice rows), or boolean DataFrame (set values based on some criterion)         |
| df.loc[val]         | Selects single row or subset of rows from the DataFrame by label                                                                                       |
| df.loc[:, val]      | Selects single column or subset of columns by label                                                                                                    |
| df.loc[val1, val2]  | Select both rows and columns by label                                                                                                                  |
| df.iloc[where]      | Selects single row or subset of rows from the DataFrame by integer position                                                                            |
| df.iloc[:, where]   | Selects single column or subset of columns by integer position                                                                                         |
| df.iloc[where_i, where_j] | Select both rows and columns by integer position                                                                                                        |
| df.at[label_i, label_j] | Select a single scalar value by row and column label                                                                                                   |
| df.iat[i, j]        | Select a single scalar value by row and column position (integers)                                                                                     |
| reindex method      | Select either rows or columns by labels                                                                                                                |
| get_value, set_value methods | Select single value by row and column label                                                                                                            |


Arithmetic and Data Alignment

In pandas, there is an interesting feature that involves arithmentic operations between onjects with different indexes. While doing addition, sometime you notice that the index pairs are not the same, the respective index in the result will be the union of the index pair. In dbms, it is sort of similar to the automatic outer join on the index labels.

In [ ]:
#for example
s1=pd.Series(np.arange(4.), index=['a', 'c', 'd','e'])
s2=pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a', 'c', 'e','f','g'])

In [ ]:
#calling both cases
s1

a    0.0
c    1.0
d    2.0
e    3.0
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
#if you add the two, you're like to get the union of the index with null values in the labels that do not overlap
s1+s2

a   -2.1
c    4.6
d    NaN
e    1.5
f    NaN
g    NaN
dtype: float64

In [ ]:
#for the case of a data frame. adding the data frames generates a data frame whose index is the union of the two initial indices.
#Check the cases below 
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

#Arithmetic methods with fill values
when performing an arithmetic operations involving two differently indexed objects, it might help to fill with special value like 0, when an axis label is found in one object but not the other. For instance.

In [ ]:
df11=pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df11

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [ ]:
df22=pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df22

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df22.loc[1,'b']=np.nan
df22

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
#if you add this two together, NA values appear in places that do not overlap
df11+df22

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
#In order to remove the np.nan value in the result, one has to pass df22 and an argumant to fill_value:
# example to show this 
df11.add(df22, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [ ]:
df11

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

Flexible arithmetic method

| Method       | Description                        |
|--------------|------------------------------------|
| add, radd    | Methods for addition (+)           |
| sub, rsub    | Methods for subtraction (-)        |
| div, rdiv    | Methods for division (/)           |
| floordiv, rfloordiv | Methods for floor division (//) |
| mul, rmul    | Methods for multiplication (*)     |
| pow, rpow    | Methods for exponentiation (**)    |


In [ ]:
#Operations between Dataframe and series (for instance, the difference between one of the rows and entire dataframe )
#consider the example below 
arr=np.arange(12.).reshape((3,4))
arr



array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
arr[0]

array([0., 1., 2., 3.])

In [ ]:
arr-arr[0] # the substraction happens row-wise. this is called broadcasting a initially discussed in the numpy tutorial. 

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                      columns=list('bde'),
                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
series =frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [ ]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
#If an index value is not found in either the DataFrame’s columns or the Series’s index,
#the objects will be reindexed to form the union
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [ ]:
frame 

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Function Application and Mapping 

NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [3]:
frame=pd.DataFrame(np.random.rand(4,3), columns=list('bde'), 
                   index=['Itah','Ohio','Texas','Oregon'])
frame

b         d         e
Itah    0.985274  0.124673  0.264206
Ohio    0.484882  0.429273  0.562290
Texas   0.354750  0.796133  0.144123
Oregon  0.499994  0.648643  0.456939

In [4]:
#Another frequent operation is applying a function on one-dimensional arrays to each
#column or row. DataFrame’s apply method does exactly this:
f=lambda x:x.max()-x.min()
frame.apply(f)
#Here the function f, which computes the difference between the maximum and minimum 
# of a Series, is invoked once on each column in frame. The result is a Series having the columns of frame as its index.



b    0.630524
d    0.671460
e    0.418167
dtype: float64

In [5]:
#If you pass axis='columns' to apply, the function will be invoked once per row instead:
frame.apply(f, axis='columns')

Itah      0.860601
Ohio      0.133018
Texas     0.652010
Oregon    0.191704
dtype: float64

In [6]:
#The function passed to apply need not return a scalar value; it can also return a Series with multiple values:
def f(x):
    return pd.Series([x.max(),x.min()],index=['max', 'min'])
frame.apply(f)

b         d         e
max  0.985274  0.796133  0.562290
min  0.354750  0.124673  0.144123

In [12]:
#Element-wise Python functions can be used, too. Suppose you wanted to compute a
#formatted string from each floating-point value in frame. You can do this with apply map
format = lambda x: '%.2f' % x
frame.applymap(format)

C:\Users\PC\AppData\Local\Temp\ipykernel_22504\3499122788.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)


b     d     e
Itah    0.99  0.12  0.26
Ohio    0.48  0.43  0.56
Texas   0.35  0.80  0.14
Oregon  0.50  0.65  0.46

In [13]:
#The reason for the name applymap is that Series has a map method for applying an
#element-wise function:
frame['e'].map(format)

Itah      0.26
Ohio      0.56
Texas     0.14
Oregon    0.46
Name: e, dtype: object