In [1]:
import numpy as np
import time


In [2]:
my_arr=np.arange(100000)

In [3]:
my_list=list(range(100000))

In [4]:
t1=time.time()
for num in my_arr:
    num *2
t2=time.time()
t_diff=t2-t1

print(t_diff)
    

0.0712575912475586


In [5]:
t1=time.time()
for num in my_list:
    num*2
t2=time.time()
t_diff=t2-t1
print(t_diff)


0.03197073936462402


# The NumPy ndarray: A Multidimensional Array Object

In [6]:
#random numbers sampled from a normal(gaussian) distribution with mean 3 and standard deviation 2.5.
data=3 + 2.5 * np.random.randn(2, 4)
data

array([[ 5.6084768 , -0.07296803,  8.5080704 ,  5.62935183],
       [ 4.86146226, -1.27152693,  6.32160989,  5.58770557]])

In [7]:
#summing the data array with itself;
#it performs the normal matrix operations
su_m=data+data 
su_m

array([[11.21695359, -0.14593606, 17.0161408 , 11.25870365],
       [ 9.72292452, -2.54305385, 12.64321979, 11.17541114]])

In [8]:
#multiplying the data array with itself;
#it performs the normal matrix operations
mult=data*data
mult

array([[3.14550120e+01, 5.32433312e-03, 7.23872620e+01, 3.16896020e+01],
       [2.36338153e+01, 1.61678072e+00, 3.99627516e+01, 3.12224535e+01]])

# Creating ndarrays

In [9]:
#using the array function, array();

data=[2,3,4,5,6,7,8,9,0]
arr=np.array(data)
arr

array([2, 3, 4, 5, 6, 7, 8, 9, 0])

In [10]:
#Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr1=np.array(data2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#outputting the dimesions of the arr1
print(arr1.ndim)
arr1.shape

2


(2, 4)

In [12]:
#checking for the data type of the arrays:The data type is stored 
#in a special dtype metadata object
arr1.dtype

dtype('int32')

In [13]:
#other functions for creating new arrays are np.empty,np.zeros or np.ones for exampe;

np.zeros((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2, 3, 2))

array([[[1.10084567e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 5.28785499e+174]],

       [[4.91132050e-062, 1.18942053e-075],
        [9.50599739e+169, 5.49557384e+174],
        [1.91857487e-076, 2.70139032e-056]]])

In [15]:
#arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#identity matrix of 3X3

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [17]:
#The data type or dtype is a special object containing the information (or metadata,data about data) 
#the ndarray needs to interpret a chunk of memory as a particular type of data

#assigning the float dtype to the array
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [18]:
#assigning the int dtype to the array
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

In [19]:
#You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method
arr=np.array([1,2,4,5,6,7], dtype=np.int64).astype(np.float64)
arr


array([1., 2., 4., 5., 6., 7.])

In [20]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [21]:
#There are shorthand type code strings you can also use to refer to a dtype:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32


array([       1,        1,        0,      518,     1148,        0,
       16777984,      518], dtype=uint32)

In [22]:
np.empty((2, 3, 2))

array([[[1.10084567e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 5.28785499e+174]],

       [[4.91132050e-062, 1.18942053e-075],
        [9.50599739e+169, 5.49557384e+174],
        [1.91857487e-076, 2.70139032e-056]]])

# Data types for ndarrays

In [23]:
#; NumPy aliases the Python types to its own equivalent data dtypes
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([    0,     1,     0,   518,  1052,     0,   768, 32764],
      dtype=uint32)

In [25]:
np.zeros(2)

array([0., 0.])

# Basic Indexing and Slicing

In [26]:
#one and two dimensional Array
data=np.array([0,1,2,3,4,5,6,7,8,9]).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#slicing 
data=np.array([0,1,2,3,4,5,6,7,8,9])
array=data[5:8]=12 #replacing the values. The replace values appear in the original Array. 
print(array)
print(data)

12
[ 0  1  2  3  4 12 12 12  8  9]


In [28]:
array1=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]], dtype=np.float64)
array1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [29]:
old_values=array1[0].copy()

In [30]:
#elements in higher dimensional arrays can take both arrays and scalar values
#example with a scalar
array1[0]=42
array1

array([[[42., 42., 42.],
        [42., 42., 42.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [31]:
# example with an array
array1[0]=old_values
array1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [32]:
# let consider slicing a 2-dimensional array, 
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]] )
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
ar1[:1]

array([[1, 2, 3]])

## Universal Functions: fast Element-Wise Array Functions

In [34]:
#a universal function, ufunc, is a function tht performs element wise operations on data in ndarrays
#you can of them as a fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scarlar results
# They include sqrt(), exp()and many more (simple element wise transformations)

In [36]:
#example 1
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#example 2
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [38]:
#example 2
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

The above ufuncs that take one scalar and produce more are call Unary ufuncs. Others which that take 2 arrays and return a single array as the result are called binary unfuncs

In [41]:
#example of binary ufuncs
x=np.random.randn(8)
y=np.random.randn(8)

In [42]:
x

array([ 0.0513242 , -0.04870899, -0.02255191,  0.60245053,  1.05074555,
        0.76082068,  0.30335857, -1.19677288])

In [44]:
y

array([ 0.12457179,  1.10545676,  0.88167727, -0.38162843,  0.82733509,
       -0.99731132, -1.42637021, -0.59141684])

In [45]:
#Example 1 -Here, numpy.maximum computed the element-wise maximum of the elements in x and y.

np.maximum(x,y)

array([ 0.12457179,  1.10545676,  0.88167727,  0.60245053,  1.05074555,
        0.76082068,  0.30335857, -0.59141684])

while not common, a ufunc can return multiple arrays.modf is one example, a vectorized version of the built-in python divmod; it returns the fractional and integral parts of a floating-point array:

In [47]:
#example
arr=np.random.rand(7)*5

In [48]:
arr

array([2.93180233, 1.17668559, 0.11307988, 4.06939846, 2.53727163,
       2.72143802, 4.06254848])

In [51]:
remainder,whole_part=np.modf(arr)
print(remainder)
print(whole_part)

[0.93180233 0.17668559 0.11307988 0.06939846 0.53727163 0.72143802
 0.06254848]
[2. 1. 0. 4. 2. 2. 4.]


Additionally, ufuncs accept an optional out argument that allows them to operate in-place on arrays


In [54]:
arr[1]=-2.93180233
arr

array([ 2.93180233, -2.93180233,  0.11307988,  4.06939846,  2.53727163,
        2.72143802,  4.06254848])

In [55]:
np.sqrt(arr)

C:\Users\PC\AppData\Local\Temp\ipykernel_6948\2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([1.71225066,        nan, 0.33627353, 2.01727501, 1.59288155,
       1.64967816, 2.01557646])