In [1]:
import numpy as np
import time


In [2]:
my_arr=np.arange(100000)

In [3]:
my_list=list(range(100000))

In [4]:
t1=time.time()
for num in my_arr:
    num *2
t2=time.time()
t_diff=t2-t1

print(t_diff)
    

0.09474563598632812


In [5]:
t1=time.time()
for num in my_list:
    num*2
t2=time.time()
t_diff=t2-t1
print(t_diff)


0.03490567207336426


# The NumPy ndarray: A Multidimensional Array Object

In [6]:
#random numbers sampled from a normal(gaussian) distribution with mean 3 and standard deviation 2.5.
data=3 + 2.5 * np.random.randn(2, 4)
data

array([[ 5.75286058,  2.35435335,  2.77739654, -2.88450538],
       [ 0.29027245,  1.05739999,  2.3372738 ,  1.23033539]])

In [7]:
#summing the data array with itself;
#it performs the normal matrix operations
su_m=data+data 
su_m

array([[11.50572117,  4.70870669,  5.55479307, -5.76901075],
       [ 0.5805449 ,  2.11479998,  4.67454759,  2.46067078]])

In [8]:
#multiplying the data array with itself;
#it performs the normal matrix operations
mult=data*data
mult

array([[33.09540489,  5.54297967,  7.71393152,  8.32037127],
       [ 0.0842581 ,  1.11809474,  5.4628488 ,  1.51372517]])

# Creating ndarrays

In [9]:
#using the array function, array();

data=[2,3,4,5,6,7,8,9,0]
arr=np.array(data)
arr

array([2, 3, 4, 5, 6, 7, 8, 9, 0])

In [10]:
#Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr1=np.array(data2)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
#outputting the dimesions of the arr1
print(arr1.ndim)
arr1.shape

2


(2, 4)

In [12]:
#checking for the data type of the arrays:The data type is stored 
#in a special dtype metadata object
arr1.dtype

dtype('int32')

In [13]:
#other functions for creating new arrays are np.empty,np.zeros or np.ones for exampe;

np.zeros((3,6))


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2, 3, 2))

array([[[1.08643768e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78019082e-306, 6.82116729e-043]],

       [[4.46920089e-090, 5.19412485e+170],
        [1.52533404e-052, 5.34965183e-038],
        [3.99910963e+252, 1.39506508e-075]]])

In [15]:
#arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#identity matrix of 3X3

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types for ndarrays

In [17]:
#The data type or dtype is a special object containing the information (or metadata,data about data) 
#the ndarray needs to interpret a chunk of memory as a particular type of data

#assigning the float dtype to the array
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1

array([1., 2., 3.])

In [18]:
#assigning the int dtype to the array
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3])

In [19]:
#You can explicitly convert or cast an array from one dtype to another using ndarray’s astype method
arr=np.array([1,2,4,5,6,7], dtype=np.int64).astype(np.float64)
arr


array([1., 2., 4., 5., 6., 7.])

In [20]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(np.float64)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [21]:
#There are shorthand type code strings you can also use to refer to a dtype:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32


array([4128860, 6029375, 3801155, 5570652, 6619251, 7536754, 7667804,
       6619251], dtype=uint32)

In [22]:
np.empty((2, 3, 2))

array([[[1.08643768e-311, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.78019082e-306, 6.82116729e-043]],

       [[4.46920089e-090, 5.19412485e+170],
        [1.52533404e-052, 5.34965183e-038],
        [3.99910963e+252, 1.39506508e-075]]])

# Data types for ndarrays

In [23]:
#; NumPy aliases the Python types to its own equivalent data dtypes
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([      0,       1,       0, 5570652,     488,       0,     768,
             0], dtype=uint32)

In [25]:
np.zeros(2)

array([0., 0.])

# Basic Indexing and Slicing

In [26]:
#one and two dimensional Array
data=np.array([0,1,2,3,4,5,6,7,8,9]).reshape(2,5)
data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#slicing 
data=np.array([0,1,2,3,4,5,6,7,8,9])
array=data[5:8]=12 #replacing the values. The replace values appear in the original Array. 
print(array)
print(data)

12
[ 0  1  2  3  4 12 12 12  8  9]


In [36]:
array1=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]], dtype=np.float64)
array1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [37]:
old_values=array1[0].copy()

In [40]:
#elements in higher dimensional arrays can take both arrays and scalar values
#example with a scalar
array1[0]=42
array1

array([[[42., 42., 42.],
        [42., 42., 42.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [39]:
# example with an array
array1[0]=old_values
array1

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 8.,  9., 10.],
        [11., 12., 13.]]])

In [49]:
# let consider slicing a 2-dimensional array, 
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]] )
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
ar1[:1]

array([[1, 2, 3]])