In [1]:
pip install numpy

In [5]:
!pip install tabulate
from tabulate import tabulate

# Your data
data = [["Name", "Age", "City"],
        ["Alice", 30, "New York"],
        ["Bob", 22, "Boston"],
        ["Charlie", 35, "Chicago"]]

# Print the table
print(tabulate(data, headers="firstrow", tablefmt="grid"))

+---------+-------+----------+
| Name    |   Age | City     |
+=========+=======+==========+
| Alice   |    30 | New York |
+---------+-------+----------+
| Bob     |    22 | Boston   |
+---------+-------+----------+
| Charlie |    35 | Chicago  |
+---------+-------+----------+


In [6]:
# Your data
data = [["Name", "Age", "City"],
        ["Alice", 30, "New York"],
        ["Bob", 22, "Boston"],
        ["Charlie", 35, "Chicago"]]

# Determine the maximum width of each column
widths = [max(map(len, str(column))) for column in zip(*data)]

# Print the table
for row in data:
    print(" | ".join((str(item).ljust(width) for item, width in zip(row, widths))))

Name | Age | City
Alice | 30 | New York
Bob | 22 | Boston
Charlie | 35 | Chicago


In [7]:
w1,w2,w3=0.3,0.2,0.5

In [8]:
kanto_temp=73
kanto_rainfall=67
kanto_humidity=43

In [9]:
kanto_yield_apples=kanto_temp*w1+kanto_rainfall*w2+kanto_humidity*w3
print(f"The expected yield of Apples in Kanto is {kanto_yield_apples} per hectare.")

The expected yield of Apples in Kanto is 56.8 per hectare.


In [10]:
#The zip() function in Python is used to combine two or more iterable dicti-
    #onaries into a single iterable, where corresponding elements from the input ite-
    #rable are paired together as tuples
name = [ "Manjeet", "Nikhil", "Shambhavi", "Astha" ]
roll_no = [ 4, 1, 3, 2 ]
 
# using zip() to map values
mapped = zip(name, roll_no)
 
print(set(mapped))

{('Shambhavi', 3), ('Astha', 2), ('Nikhil', 1), ('Manjeet', 4)}


In [11]:
kanto=[73,67,43]
johto=[91,88,64]
hoenn=[87,134,58]
sinnoh=[102,134,58]
unova=[69,96,70]
weights=[w1,w2,w3]  

In [12]:
#performimg the dot product of a vector 
def crop_yield(region, weights):
    result=0
    
    for x, w in zip(region, weights):
        
        result+=x*w
    return(result) 
     

In [13]:
crop_yield(kanto,weights)

56.8

In [14]:
crop_yield(johto, weights)

76.9

In [15]:
crop_yield (sinnoh, weights)

86.4

In [16]:
# python provides a library that can be used to perform dot products called numpy
import numpy as np

In [17]:
#before proceeding, it is import to convert all data into arrays
#This allows for easy interaction between the data and numpy
kanto=np.array([73,67,56])

In [18]:
kanto

array([73, 67, 56])

In [19]:
weights=np.array([w1,w2,w3])

In [20]:
type(weights)

numpy.ndarray

In [21]:
#just like lists, array also support indexing notation
weights[0]

0.3

In [22]:
 #we can now calculate the dot product 
np.dot(kanto,weights)

63.3

In [23]:
#individual multiplication of the two variables kanto and wights would just give the element-wise multiplication
#of the two vectors
#example
kanto*weights

array([21.9, 13.4, 28. ])

In [24]:
#We can also arrive at the dot product by passing the sum()to the above code
#example 
(kanto*weights).sum()

63.3

## Multi-dimensional Arrays

In [25]:
climate_data=np.array([[72,67,43],
             [91,88,64],
             [87,134,58],
              [102,43,37],
              [69,96,70]])

In [26]:
climate_data

array([[ 72,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [27]:
#2D array(matrix)
#checking for the dimension of arrays. The above is a 2 dimensional Array
climate_data.shape

(5, 3)

In [28]:
#3D array
arry1=np.array([[[1,2,3],[2,3,4]], [[4,5,6],[6,8,9]]])

In [29]:
arry1.shape

(2, 2, 3)

In [30]:
#ALL ELEMENTS IN AN ARRAY HAVE THE SAME DATA TYPES
#EVEN IF ONLY ONE OF THE ELEMENTS IS A FLOAT, ALL THE OTHER ELEMENTS WILL BE CONVERTED INTO FLOATS.

In [31]:
#numpy has it own function that does dot matrix multiplication
#the matmul() function 
np.matmul(climate_data, weights)

array([56.5, 76.9, 81.9, 57.7, 74.9])

In [32]:
#another to do the samething is to use the @ character which represent matrix multiplication in numpy
#example 
climate_data @ weights

array([56.5, 76.9, 81.9, 57.7, 74.9])

# Working with CSV files

In [33]:
from tabulate import tabulate
climate_data2=[["temperature", "rainfall","humidity"],
              [25,76,99],
              [39,65,70],
              [59,45,77],
              [84,63,38],
              [66,50,52],
              [41,94,77],
              [91,57,96],
              [49,96,99],
              [67,20,28],
              [85,31,95]]
# Convert the tabulated data to a CSV-like string
climate_data_csv = '\n'.join([','.join(map(str, row)) for row in climate_data2[1:]])

# Now, load the CSV-like string into a NumPy array
climate_data = np.genfromtxt(np.array(climate_data_csv.splitlines()), delimiter=',', dtype=None, skip_header=0)

print(climate_data)


[[25 76 99]
 [39 65 70]
 [59 45 77]
 [84 63 38]
 [66 50 52]
 [41 94 77]
 [91 57 96]
 [49 96 99]
 [67 20 28]
 [85 31 95]]


In [34]:
climate_data.shape

(10, 3)

In [35]:
yields=climate_data@weights

In [36]:
yields.shape

(10,)

In [37]:
 yields

array([72.2, 59.7, 65.2, 56.8, 55.8, 69.6, 86.7, 83.4, 38.1, 79.2])

In [38]:
#to add the yields a column to the climate_data, we use the np.concatenate function
#example
#The reshape(10,1) function call reshapes the yields array into a 2D array with 10 rows and 1 column. 
#This is necessary for concatenation because the dimensions of the arrays being concatenated must match along the concatenation axis.
climate_results=np.concatenate((climate_data,yields.reshape(10,1)),axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       [84. , 63. , 38. , 56.8],
       [66. , 50. , 52. , 55.8],
       [41. , 94. , 77. , 69.6],
       [91. , 57. , 96. , 86.7],
       [49. , 96. , 99. , 83.4],
       [67. , 20. , 28. , 38.1],
       [85. , 31. , 95. , 79.2]])

In [39]:
#'climate_results.txt': This is the filename where the data will be saved.

#climate_results: This is the data array to be saved to the file.

#fmt='%.2f': This specifies the format string for the data. In this case, it's '%.2f', which means floating-point numbers with two decimal places.

#header='temperature,rainfall,humidity,yields_apples': This specifies the header to be written at the beginning of the file. It labels the columns of the data with the corresponding variables: temperature, rainfall, humidity, and yields_apples.

#comments='': This specifies that no comment string will be inserted at the beginning of the file.
np.savetxt('climate_results.txt',
           climate_results,
          fmt='%.2f',
          header='temperature,rainfall,humidity,yields_apples',
          comments='')

# Arithmetic Operations and Broadcasting 

In [40]:
#numpy arrays allows for broadcasting-arithmetic operations b2n two array having a different number of dimensions, but compatible shapes. 
#broadcasting only works if one of the arrays can replicated to the dimensionality of the other.
#example

array2=np.array ([[1,3,4,54],
                [4,6,4,6],
                [6,7,8,2]])

In [41]:
array2.shape

(3, 4)

In [42]:
array4=np.array([4,6,7,7])

In [43]:
array4.shape

(4,)

In [44]:
array2+array4

array([[ 5,  9, 11, 61],
       [ 8, 12, 11, 13],
       [10, 13, 15,  9]])

# Indexing and slicing with Arrays

In [45]:
import numpy as np
arr1=np.array([[[11,23,12,14],
              [14,34,14,18]],
             [[13,14,12,15],
              [14,17,19,19]],
             [[13,15,16,18],
              [15,16,19,34]]])


In [46]:
arr1[1,1,2]

19

In [47]:
# 1: means that we taking everything minus the 0th element in the outermost list
# 0:1 means only taking index 0 to 1 in the second dimension without the 1
#:2 means taking taking upto index[1] in last dimension 
arr1[1:,0:1,:2]

array([[[13, 14]],

       [[13, 15]]])

In [48]:
arr1.shape

(3, 2, 4)

# Other ways of creating Arrays in Numpy

In [49]:
#all zeros
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
# identity matrix
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [51]:
# random vector 
#generating an array of five random numbers
np.random.rand(5)

array([0.62992412, 0.69671419, 0.23035424, 0.43837138, 0.84696882])

In [52]:
# matrix
#example: generating and array of five random numbers between 2(inclusive) and 4(exclusive)
np.random.randint(2,4,5)

array([3, 2, 2, 2, 2])

In [53]:
#a 2x4 array with random numbers drawn from a standard normal distribution (mean 0 and variance 1)
np.random.randn(2,4)

array([[ 0.84912798,  1.00379191,  1.16482727,  1.2642578 ],
       [ 1.64306248,  1.93365082, -1.24146416,  0.22483428]])

In [54]:
#creating an array based on a fixed value
#example: dim is (2x3):fixed value is 4
np.full((2,3), 4)

array([[4, 4, 4],
       [4, 4, 4]])

In [55]:
#arranging numbers constantly increasing. 
#Example: Starts with 4, increases with 2 and ends with 20-2 
np.arange(4,20,2)


array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
#Equally  space numbers in a range 
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [57]:
np.arange(10,90,3).reshape(3,3,-1)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])